[env]
BIN_NAME = "timer"

[settings]
experimental = true

[tools]
"go:github.com/spf13/cobra-cli" = "latest"

[tasks]
[tasks.build]
description = "build executable"
run = 'go build -o ./bin/$BIN_NAME .'

[tasks.run]
description = "run the executable"
depends = ["build"]
run = "./bin/$BIN_NAME"
